---
title: "My publications"
bibliography: references.bib
csl: new-zealand-plant-protection (CEB).csl
# https://gsverhoeven.github.io/post/zotero-rmarkdown-csl/
#bibliography: references.bib
---

# Publication topics

-   Weed focused papers in New Zealand [@bourdotPastoralSectorWeeds2018; @buddenhagenBroomControlMonitoring2000; @buddenhagenCostsRisksAssociated2019; @buddenhagenResistancePostemergentHerbicides2021; @buddenhagenPhytosanitaryRisksPosed2021; @buddenhagenWarWeeds2000; @dowsettPredictingMassEmergence2018; @dowsettYellowBristleGrass2018; @flynnWaitakereCityWeed2000; @ghanizadehGeneticInheritanceHerbicide2019; @ghanizadehPCRRestrictionEnzymebased2021; @ghanizadehPinoxadenResistanceLolium2022; @gordonWeedRiskAssessments2016; @ngowHerbicideResistanceRisk2020; @ngowHerbicideResistanceRisk2021; @10.1371/journal.pone.0256623; @timminsNewZealandWeedy2000; @doi:10.1080/00288233.2022.2107026; @buddenhagen_etal98]
-   Weed reports global [@buddenhagenCarexKobomugiAsiatic2015; @buddenhagenSetpar13; @buddenhagenCyclosorusParasiticusParasitic2013; @buddenhagenSolanumCapsicoidesCockroach2014; @buddenhagenPassifloraEdulisPassionfruit2014; @buddenhagenChristellaDentataSoft2014; @buddenhagen15a; @buddenhagenAssessingBiofuelCrop2009; @chimeraBiofuelsRisksDangers2010; @gordonWeedRiskAssessments2016]
-   Invasive plant focused papers from Galapagos [@buddenhagenSuccessfulEradicationTwo2006; @buddenhagenControlHighlyInvasive2004; @buddenhagenLessonsSuccessfulPlant2015; @buddenhagenInvasivePlantSeed2006; @buddenhagenCostQuinineCinchona2005; @gardenerPragmaticApproachManagement2013; @guerreroBaselineDataIdentifying2008; @guezouPreventingEstablishmentInventory2007; @guezouExtensiveAlienPlant2010; @renteriaInvasivePlantsScalesia2006; @roggExperiencesLimitationsPest2003]
-   Plant epidemiology and plant pathology [@andersenModelingEpidemicsSeed2019; @buddenhagenWhereInvestProject2022; @buddenhagenEpidemicNetworkAnalysis2017; @garrettNetworkAnalysisSystems2018; @10.1371/journal.pone.0256623]
-   Seed biosecurity and seed systems [@andersenModelingEpidemicsSeed2019; @buddenhagenWhereInvestProject2022; @buddenhagenEpidemicNetworkAnalysis2017; @buddenhagenPhytosanitaryRisksPosed2021; @buddenhagenInvasivePlantSeed2006; @dowsettPredictingMassEmergence2018; @dowsettYellowBristleGrass2018; @10.1371/journal.pone.0256623]
-   Plant evolution [@buddenhagenViewRhynchosporeaeCyperaceae2016; @buddenhagen_etal17; @burchardtHolocentricKaryotypeEvolution2020; @caiPerfectStormGene2021; @10.1093/aob/mcab063; @ribeiroAreHolocentricsDoomed2018; @10.1093/aob/mcab063]

# References
